version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"
    steps:
      - checkout
      - run:
          name: Run Tests
          command: fastlane scan --project "MeshKit.xcodeproj" --scheme "MeshKit-iOS" --device "iPhone X" --clean
workflows:
  version: 2
  workflow:
    jobs:
    - build-and-test